'use strict';
let data,activeDay=1,map,markers=[],mapLoaded=false;
let fallbackScale=1,fallbackX=0,fallbackY=0,mapExpanded=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=d=>`assets/${d.image}.png`;
const dateLabel=d=>new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',timeZone:'Asia/Makassar'}).format(new Date(d.date+'T12:00:00+08:00'));
function mapStops(d){const grouped=new Map();for(const s of d.route_stops||d.stops){if(grouped.has(s.id)){const p=grouped.get(s.id);p.number+='·'+s.number;}else grouped.set(s.id,{...s,number:String(s.number)});}return [...grouped.values()];}
function tripPoints(d){return [data.hotel,...(d.island?data.logistics_points.filter(p=>p.role==='port'):[]),...mapStops(d),...(d.last?data.logistics_points.filter(p=>p.role==='airport'):[])].filter(p=>p.lon!=null&&p.lat!=null);}
function fitPoints(points,maxZoom=13){if(!mapLoaded||!points.length)return;const bounds=points.reduce((b,p)=>b.extend(p),new maplibregl.LngLatBounds(points[0],points[0]));map.fitBounds(bounds,{padding:map.getContainer().clientWidth>600?{top:110,bottom:110,left:130,right:130}:{top:55,bottom:70,left:45,right:45},duration:0,maxZoom});}
function fitDay(d,mode='all'){fitPoints(mode==='island'?[...mapStops(d).filter(p=>p.lon>115.4),data.logistics_points.find(p=>p.id==='penida-port')].filter(p=>p.lon!=null).map(p=>[p.lon,p.lat]):[...d.legs.flatMap(l=>l.geometry?.coordinates||[]),...tripPoints(d).map(p=>[p.lon,p.lat])]);}
function renderMap(d){if(!mapLoaded)return;
 const geo={type:'FeatureCollection',features:d.legs.filter(l=>l.geometry).map(l=>({type:'Feature',properties:{index:l.index,returning:l.returning},geometry:l.geometry}))};
 if(map.getSource('route'))map.getSource('route').setData(geo);else{
 map.addSource('route',{type:'geojson',data:geo});
 map.addLayer({id:'route-white',type:'line',source:'route',layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#ffffff','line-width':8}});
 map.addLayer({id:'route-out',type:'line',source:'route',filter:['==',['get','returning'],false],layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#235749','line-width':4}});
 map.addLayer({id:'route-back',type:'line',source:'route',filter:['==',['get','returning'],true],paint:{'line-color':'#c47850','line-width':4,'line-dasharray':[2,1.5]}});
 map.addLayer({id:'route-highlight',type:'line',source:'route',filter:['==',['get','index'],-1],paint:{'line-color':'#e2ac3e','line-width':7}});
 const canvas=document.createElement('canvas');canvas.width=20;canvas.height=20;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.strokeStyle='#235749';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(3,3);ctx.lineTo(17,10);ctx.lineTo(3,17);ctx.closePath();ctx.fill();ctx.stroke();map.addImage('bali-route-arrow',ctx.getImageData(0,0,20,20));
 map.addLayer({id:'route-directions',type:'symbol',source:'route',layout:{'symbol-placement':'line','symbol-spacing':100,'icon-image':'bali-route-arrow','icon-size':.7,'icon-allow-overlap':true,'icon-rotation-alignment':'map'}});
 }
 map.setFilter('route-highlight',['==',['get','index'],-1]);markers.forEach(m=>m.remove());markers=[];
 for(const p of tripPoints(d)){const element=document.createElement('button');element.className='map-pin'+(p.role==='hotel'?' home':p.role==='port'?' port':p.role==='meal'?' meal':'');element.textContent=p.number||(p.role==='hotel'?'⌂':p.role==='port'?'⚓':'✈');element.setAttribute('aria-label',p.name);const content=document.createElement('div');content.className='pin-title';const name=document.createElement('strong');name.textContent=p.name;content.append(name);const a=document.createElement('a');a.href=p.place_url;a.target='_blank';a.rel='noopener';a.textContent='Открыть место ↗';content.append(a);markers.push(new maplibregl.Marker({element,offset:p.id==='v05'?[-12,-8]:p.id==='v06'?[12,8]:p.id==='r18'?[-14,-14]:p.id==='r43'?[14,14]:[0,0]}).setLngLat([p.lon,p.lat]).setPopup(new maplibregl.Popup({offset:18}).setDOMContent(content)).addTo(map));}
 const labels={type:'FeatureCollection',features:mapStops(d).filter(p=>p.lon!=null).map(p=>({type:'Feature',geometry:{type:'Point',coordinates:[p.lon,p.lat]},properties:{name:`${p.number}. ${p.name}`,role:p.role}}))};
 if(map.getSource('stop-labels'))map.getSource('stop-labels').setData(labels);else{map.addSource('stop-labels',{type:'geojson',data:labels});map.addLayer({id:'stop-names',type:'symbol',source:'stop-labels',layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':11,'text-variable-anchor':['bottom','top','left','right'],'text-radial-offset':1.7,'text-max-width':13},paint:{'text-color':'#173f37','text-halo-color':'#fff','text-halo-width':2}});}
 fitDay(d);window.__guide.currentMapDay=d.number;
}
function mapError(message){
 if(mapLoaded){$('mapFallback').hidden=true;$('mapState').hidden=true;$('mapNotice').textContent='Часть подложки не загрузилась. Масштаб и перемещение работают; недостающие фрагменты могут появиться при следующем увеличении.';return;}
 $('mapState').hidden=false;$('mapState').classList.add('error-state');$('mapState').textContent=message+' Сохранённую карту можно увеличить кнопками + / − и перетаскивать.';$('mapFallback').hidden=false;
}
function drawFallback(){
 const box=$('mapFallback').parentElement;fallbackX=Math.max(-box.clientWidth*(fallbackScale-1)/2,Math.min(box.clientWidth*(fallbackScale-1)/2,fallbackX));fallbackY=Math.max(-box.clientHeight*(fallbackScale-1)/2,Math.min(box.clientHeight*(fallbackScale-1)/2,fallbackY));
 $('mapFallback').style.transform=`translate(${fallbackX}px,${fallbackY}px) scale(${fallbackScale})`;
}
function resetMapView(){fallbackScale=1;fallbackX=fallbackY=0;drawFallback();fitDay(data.days[activeDay-1]);}
function zoomMap(delta){if(mapLoaded&&$('mapFallback').hidden){map.zoomTo(map.getZoom()+delta,{duration:180});return;}fallbackScale=Math.max(1,Math.min(8,fallbackScale*(delta>0?1.5:1/1.5)));drawFallback();}
function expandMap(expanded=!mapExpanded){
 mapExpanded=expanded;$('map-section').classList.toggle('map-expanded',expanded);document.body.classList.toggle('map-open',expanded);
 const b=$('mapFullscreen');b.setAttribute('aria-expanded',String(expanded));b.setAttribute('aria-label',expanded?'Закрыть полноэкранную карту':'Развернуть карту на весь экран');b.title=expanded?'Закрыть карту · Esc':'На весь экран';b.textContent=expanded?'×':'⤢';
 requestAnimationFrame(()=>{map?.resize();drawFallback();});b.focus({preventScroll:true});
}
function initMapControls(){
 $('mapZoomIn').onclick=()=>zoomMap(1);$('mapZoomOut').onclick=()=>zoomMap(-1);$('fitRoute').onclick=resetMapView;$('mapFullscreen').onclick=()=>expandMap();
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mapExpanded){e.preventDefault();expandMap(false);}});
 const img=$('mapFallback');img.draggable=false;const pointers=new Map();let drag=null,pinchDistance=0,pinchScale=1;
 img.addEventListener('pointerdown',e=>{e.preventDefault();img.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={x:e.clientX,y:e.clientY,ox:fallbackX,oy:fallbackY};if(pointers.size===2){const [a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y);pinchScale=fallbackScale;}});
 img.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];fallbackScale=Math.max(1,Math.min(8,pinchScale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinchDistance)));}else if(drag){fallbackX=drag.ox+e.clientX-drag.x;fallbackY=drag.oy+e.clientY-drag.y;}drawFallback();});
 const release=e=>{pointers.delete(e.pointerId);drag=null;};img.addEventListener('pointerup',release);img.addEventListener('pointercancel',release);
 img.addEventListener('wheel',e=>{e.preventDefault();zoomMap(e.deltaY<0?1:-1);},{passive:false});img.addEventListener('dblclick',()=>zoomMap(1));
 new ResizeObserver(()=>{map?.resize();drawFallback();}).observe(img.parentElement);
}
function initMap(){try{if(!window.maplibregl)throw new Error('Библиотека карты не загрузилась');map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[115.18,-8.8],zoom:10,attributionControl:false,preserveDrawingBuffer:true});window.__guide.map=map;map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');map.addControl(new maplibregl.AttributionControl({compact:false}),'bottom-right');map.on('load',()=>{mapLoaded=true;$('mapState').hidden=true;$('mapFallback').hidden=true;window.__guide.map=map;window.__guide.mapLoaded=true;renderMap(data.days[activeDay-1]);});map.on('error',e=>{window.__guide.mapErrors.push(String(e.error?.message||e.error));mapError('Интерактивная карта пока недоступна. Показана сохранённая карта дня; расписание и навигационные ссылки доступны.');});setTimeout(()=>{if(!mapLoaded)mapError('Карта загружается дольше обычного. Проверьте интернет и обновите страницу.');},20000);}catch(e){mapError('Не удалось открыть карту: '+e.message);}}
function selectLeg(index){const leg=data.days[activeDay-1].legs[index];document.querySelectorAll('.road-row').forEach(b=>b.classList.toggle('selected',Number(b.dataset.leg)===index));if(!mapLoaded||!leg.geometry||!$('mapFallback').hidden){$('mapNotice').textContent='Выбран переезд: '+leg.key+'. Сейчас показана сохранённая карта; для выделения участка нужен интерактивный режим. Ссылка на этот переезд доступна в расписании.';return;}map.setFilter('route-highlight',['==',['get','index'],index]);fitPoints(leg.geometry.coordinates,15);}
function focusStop(id){const p=(data.days[activeDay-1].route_stops||data.days[activeDay-1].stops).find(s=>s.id===id);if(p?.lon!=null&&mapLoaded&&$('mapFallback').hidden){map.flyTo({center:[p.lon,p.lat],zoom:14});markers.find(m=>m.getElement().getAttribute('aria-label')===p.name)?.togglePopup();}else $('mapNotice').textContent='Сейчас показана сохранённая карта. Номер остановки и ссылка на место доступны в расписании.';}
function period(t){const h=Number(t.split(':')[0]);return h<5?'☾ Ночь':h<12?'☀ Утро':h<17?'◌ День':'☾ Вечер';}
function drawTimeline(d){let prev='';$('timeline').innerHTML=d.timeline.map(r=>{const p=period(r.start),heading=p!==prev?`<div class="period-label">${p}</div>`:'';prev=p;const interval=`${r.start}${r.end!==r.start?' – '+r.end:''}`;
 if(r.kind==='visit')return heading+`<article class="timeline-stop"><div class="stop-number">${r.number}</div><div class="stop-info"><span class="time">${interval} · ${r.duration_minutes} мин</span><h4>${esc(r.title)}</h4><p>${esc(r.note)}</p><div class="stop-actions"><button data-stop="${r.place_id}">Показать на карте</button><a href="${esc(r.place_url)}" target="_blank" rel="noopener">Открыть место ↗</a></div></div></article>`;
 if(r.kind==='road')return heading+`<button class="road-row" data-leg="${r.leg_index}"><span><strong>${esc(r.title)}</strong><small>${r.start} → ${r.end} · ${r.distance_km==null?'км не подтверждены':r.distance_km+' км'} · ${r.range_minutes.join('–')} мин</small><small>План: ${r.duration_minutes} мин · выделить участок</small></span><span class="road-arrow">↗</span></button><div class="road-navigation"><a href="${esc(r.navigation_url)}" target="_blank" rel="noopener">Открыть переезд в Google Maps ↗</a></div>`;
 if(r.kind==='meal')return heading+`<article class="meal-row ${r.meal_type==='coffee'?'coffee-row':''}" data-restaurant="${r.restaurant_id}"><span class="meal-icon">${r.number||'♧'}</span><div><span class="time">${interval} · ${r.duration_minutes} мин</span><strong>${esc(r.title)}</strong><span class="meal-badge">${r.meal_mode==='packed'?'Согласовать бокс заранее':r.booking_required?'Бронь обязательна':r.user_choice?'Ваш выбор':'Мой выбор'}</span><p>${esc(r.note)}</p>${r.meal_mode==='onsite'?`<p class="meal-hours">${esc(r.hours_label)}</p>`:''}<div class="meal-actions">${r.meal_mode==='onsite'?`<button data-stop="${r.restaurant_id}">На карте</button>`:''}<a href="${esc(r.place_url)}" target="_blank" rel="noopener">Открыть ресторан ↗</a><a href="${esc(r.source_url)}" target="_blank" rel="noopener">Источник · ${esc(r.checked)}</a></div></div></article>`;
 if(r.kind==='buffer')return heading+`<div class="buffer-row">${interval} · ${esc(r.title)}</div>`;
 return heading+`<article class="logistic-row"><span class="time">${interval}</span><strong>${r.kind==='boat'?'⚓ ':''}${esc(r.title)}</strong><p>${esc(r.note)}</p></article>`;
 }).join('');$('timeline').querySelectorAll('[data-leg]').forEach(b=>b.onclick=()=>selectLeg(Number(b.dataset.leg)));$('timeline').querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>focusStop(b.dataset.stop));}
function selectDay(n,scroll=false){if(data&&$('restaurantCoverageTable'))$('restaurantCoverageTable').innerHTML=data.restaurant_coverage.map(p=>`<div class="coverage-item"><span>${esc(p.name)}${p.id==='r15'?' · еда не подтверждена':''}</span><span>${Number(p.date.slice(-2))} окт</span></div>`).join('');activeDay=Math.max(1,Math.min(12,n));const d=data.days[activeDay-1];window.__guide.currentDay=activeDay;fallbackScale=1;fallbackX=fallbackY=0;drawFallback();$('mapFallback').src=`maps/day-${String(activeDay).padStart(2,'0')}.png`;
 $('dayHeader').innerHTML=`<div class="day-heading"><div><span class="eyebrow">ДЕНЬ ${d.number} · ${dateLabel(d).toLocaleUpperCase('ru')} · ${esc(d.weekday.toLocaleUpperCase('ru'))}</span><h2>${esc(d.title)}</h2><p>${esc(d.subtitle)}</p></div><img src="${image(d)}" alt="Сгенерированная иллюстрация для настроения дня"></div>`;
 $('daySummary').innerHTML=[['Подъём',d.wake,''],['Выезд',d.depart,''],[d.last?'Аэропорт · оценка':'Возвращение · оценка',d.return_time,''],['Дорога',`${d.distance_km_known}${d.missing_legs?' + ?':''} км`,d.island?'без морских участков':''],['Нагрузка',d.load,`${Math.floor(d.road_minutes/60)} ч ${d.road_minutes%60} мин в дороге`]].map(([label,value,note])=>`<div class="summary-item"><span>${label}</span><strong>${esc(value)}</strong>${note?`<br><small>${esc(note)}</small>`:''}</div>`).join('');drawTimeline(d);
 $('dayAdvice').innerHTML=`<h4>Почему в таком порядке</h4><p>${esc(d.why)}</p><h4>Что важно учесть</h4><p>${esc(d.risk)}</p>${d.island?`<h4>Обратный катер</h4><p>Оценка прибытия к порту: ${d.port_arrival_estimate}. Опубликованный обратный рейс — 17:00; наличие мест и регистрацию подтвердить.</p>`:''}`;
 $('restaurantAlternatives').innerHTML=`<div class="section-head"><div><span class="eyebrow">ВАШ ВЫБОР ВСЕГДА ОСТАЁТСЯ ЗА ВАМИ</span><h3>Не подходит? Выберите сами.</h3></div><a class="text-link" href="restaurants.html?day=${d.number}">Все 72 ресторана ↗</a></div><p>Мой выбор уже стоит в расписании, каждый ресторан посещается один раз. Кнопка «Поменять мой выбор» переставляет два заведения и проверяет оба дня, сохраняя покрытие без повторов. PDF содержит основной вариант; ваш выбор можно сохранить в JSON.</p><div class="alternatives-grid">${d.alternatives.map(p=>`<article><span class="eyebrow">${esc(p.area)}</span><h4>${esc(p.name)}</h4><p>${esc(p.note)}</p><small>${esc(p.hours_label)}</small><a href="${esc(p.place_url)}" target="_blank" rel="noopener">Посмотреть ресторан ↗</a></article>`).join('')}</div>`;
 $('mapNotice').textContent=d.missing_legs?'Pantai Samuh: координаты не подтверждены. Два участка не нарисованы; километраж неполный.':d.island?'Катер показан в расписании, морская геометрия не выдумывалась. Дороги включают материк и Пениду.':'Входы, парковки и пешие подходы ещё проверяются. Автомобильный расчёт не гарантирует доступ для байка.';
 $('mapLinks').replaceChildren();if(d.island){const b=document.createElement('button');b.className='secondary';b.textContent='Пенида крупно';b.onclick=()=>fitDay(d,'island');$('mapLinks').append(b);}for(const [leg,label]of[[d.legs[0],'Первый переезд ↗'],[d.legs.at(-1),'Обратно / аэропорт ↗']]){const a=document.createElement('a');a.textContent=label;a.href=leg.navigation_url;a.target='_blank';a.rel='noopener';$('mapLinks').append(a);}
 $('prevDay').disabled=activeDay===1;$('nextDay').disabled=activeDay===12;$('pageIndex').textContent=`День ${activeDay} из 12`;document.querySelectorAll('#dayNav button').forEach(b=>{const selected=Number(b.dataset.day)===activeDay;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected));});renderMap(d);document.dispatchEvent(new Event('bali-day-changed'));if(scroll){history.replaceState(null,'',`#day-${activeDay}`);$('days').scrollIntoView({behavior:'smooth'});}}
async function init(){try{const r=await fetch('itinerary.json');if(!r.ok)throw new Error('Не удалось загрузить данные маршрута');data=await r.json();window.__guide={data,currentDay:1,currentMapDay:null,mapLoaded:false,mapErrors:[],selectDay,fitDay,selectLeg};
 $('dayGrid').innerHTML=data.days.map(d=>`<button class="day-card" data-day="${d.number}" aria-label="Открыть день ${d.number}: ${esc(d.title)}"><div class="day-card-photo"><img src="${image(d)}" alt="" loading="lazy"><span class="card-day">День ${d.number}</span><span class="card-date">${dateLabel(d)} · ${esc(d.weekday)}</span></div><div class="card-body"><strong>${esc(d.title)}</strong><p>${esc(d.subtitle)}</p><div class="card-bottom"><span>${d.stops.length} мест · ${d.meals.filter(m=>m.meal_mode==='onsite').length} заведений</span><b>↗</b></div></div></button>`).join('');$('dayNav').innerHTML=data.days.map(d=>`<button data-day="${d.number}"><strong>День ${d.number}</strong>${Number(d.date.slice(-2))} окт</button>`).join('');document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.day),true));
 $('restaurantCoverageTable').innerHTML=data.restaurant_coverage.map(p=>`<div class="coverage-item"><span>${esc(p.name)}${p.id==='r15'?' · еда не подтверждена':''}</span><span>${Number(p.date.slice(-2))} окт</span></div>`).join('');
 $('coverageTable').innerHTML=data.coverage.map(p=>`<div class="coverage-item"><span>${esc(p.name)}</span><button data-date="${p.planned_date}">${Number(p.planned_date.slice(-2))} окт ↗</button></div>`).join('');document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>selectDay(data.days.find(d=>d.date===b.dataset.date).number,true));$('limitations').innerHTML=data.limitations.map(s=>`<li>${esc(s)}</li>`).join('');$('sourceLinks').innerHTML=data.sources.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a> · ${esc(s.checked)}</p>`).join('');$('prevDay').onclick=()=>selectDay(activeDay-1,true);$('nextDay').onclick=()=>selectDay(activeDay+1,true);initMapControls();selectDay(Number(location.hash.match(/^#day-(\d+)$/)?.[1]||1));initMap();$('pdfLink').hidden=false;$('downloadSection').hidden=false;
 }catch(e){$('globalError').hidden=false;$('globalError').textContent=e.message;}}
init();

