'use strict';
const requestedDay=Number(new URLSearchParams(location.search).get('day'));
const dayContext=requestedDay>=1&&requestedDay<=12?requestedDay:null;
const KEY='bali-personal-guide-selection-v1'+(dayContext?'-day-'+dayContext:'');
let registry,role='meal',chosen=new Set();
const el=id=>document.getElementById(id);
let storageWorks=true;
try{chosen=new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));}catch{storageWorks=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify([...chosen]));}catch{storageWorks=false;}}
function payload(){return {schema_version:1,day_context:dayContext,list_snapshot_date:'2026-10-06',user_updates:registry.user_updates||[],lists_unchanged_confirmed:el('unchanged').checked,selected_restaurants:registry.places.filter(p=>chosen.has(p.id)).map(p=>({id:p.id,name:p.name,place_url:p.place_url})),note:'Личный выбор; совместимость с расписанием ещё не проверена'};}
function selectionText(){const p=payload();return `${dayContext?"Замены ресторанов для дня "+dayContext+" ("+(10+dayContext)+" октября).\n":""}Списки после 6 октября: ${p.lists_unchanged_confirmed?'не менялись, подтверждаю':'актуальность пока не подтверждена'}.\nВыбрано ресторанов: ${p.selected_restaurants.length}.\n${p.selected_restaurants.map((r,i)=>`${i+1}. ${r.name}`).join('\n')}`;}
function updateSummary(){el('selectedCount').textContent=`Выбрано ${chosen.size} / 72`;el('selectionHint').textContent=!storageWorks?'Сохраните JSON: локальное хранение недоступно':chosen.size>72?'В списке всего 72 заведения':chosen.size?'Все 72 уже назначены; здесь ваш список для уточнений':'Добавьте рестораны для вашего маршрута';el('selectionText').value=selectionText();}
function draw(){const query=el('search').value.trim().toLocaleLowerCase('ru');const area=el('area').value;const records=registry.places.filter(p=>p.roles.includes(role)&&(!area||p.area.value===area)&&(!el('onlySelected').checked||chosen.has(p.id))&&(`${p.name} ${p.address.value||''}`).toLocaleLowerCase('ru').includes(query));el('resultCount').textContent=`Показано ${records.length} из ${role==='meal'?72:29} · районы предварительные`;el('cards').replaceChildren();for(const p of records){const card=document.createElement('article');card.className='card'+(chosen.has(p.id)?' chosen':'');const label=document.createElement(role==='meal'?'label':'div');label.className='label';if(role==='meal'){const cb=document.createElement('input');cb.type='checkbox';cb.checked=chosen.has(p.id);cb.setAttribute('aria-label',`Выбрать ${p.name}`);cb.addEventListener('change',()=>{if(cb.checked)chosen.add(p.id);else chosen.delete(p.id);save();updateSummary();if(el('onlySelected').checked)draw();else card.classList.toggle('chosen',cb.checked);});label.append(cb);}const name=document.createElement('span');name.textContent=p.name;label.append(name);card.append(label);const district=document.createElement('div');district.className='area';district.textContent=p.area.value;card.append(district);const address=document.createElement('p');address.textContent=p.address.value==='TBD'?'Адрес требует проверки':p.address.value||'Адрес требует проверки';card.append(address);const link=document.createElement('a');link.href=p.place_url;link.target='_blank';link.rel='noopener';link.textContent='Открыть место в Google Maps ↗';card.append(link);el('cards').append(card);}if(!records.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='Нет совпадений. Измените поиск или фильтр.';el('cards').append(empty);}}
function setRole(value){role=value;el('onlySelected').checked=false;el('onlySelected').disabled=role==='visit';el('area').replaceChildren(new Option('Все районы',''));const areas=[...new Set(registry.places.filter(p=>p.roles.includes(role)).map(p=>p.area.value))].sort((a,b)=>a.localeCompare(b));areas.forEach(a=>el('area').add(new Option(a,a)));document.querySelectorAll('.tab').forEach(b=>{const active=b.dataset.role===role;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});draw();}
async function start(){try{const response=await fetch('registry.json');if(!response.ok)throw new Error('HTTP '+response.status);registry=await response.json();if(dayContext){const h=document.createElement('p');h.className='eyebrow';h.textContent='Альтернативы для дня '+dayContext+' · '+(10+dayContext)+' октября';document.querySelector('.notice').prepend(h);}if(registry.places.length!==101)throw new Error('Неполный реестр');const valid=new Set(registry.places.filter(p=>p.roles.includes('meal')).map(p=>p.id));chosen=new Set([...chosen].filter(id=>valid.has(id)));setRole(role);updateSummary();document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setRole(b.dataset.role)));['search','area','onlySelected'].forEach(id=>el(id).addEventListener('input',draw));el('unchanged').addEventListener('change',updateSummary);el('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(selectionText());el('message').textContent='Выбор скопирован. Вставьте его в чат.';}catch{document.querySelector('details').open=true;el('selectionText').focus();el('selectionText').select();el('message').textContent='Копирование недоступно. Выделенный текст можно скопировать вручную.';}});el('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(payload(),null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='bali-restaurants-selection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}catch(error){el('error').hidden=false;el('error').textContent=`Реестр не загрузился. Откройте страницу через локальный сервер по инструкции README. Подробности: ${error.message}`;el('resultCount').textContent='Не удалось загрузить список';el('copy').disabled=true;el('download').disabled=true;}}
start();
